%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\Matlab\fileExcel.xlsx
%    Worksheet: Data
%
% Auto-generated by MATLAB on 22-Mar-2022 11:06:15

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = "Data";
opts.DataRange = "A2:B6";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["string", "categorical"];

% Specify variable properties
opts = setvaropts(opts, "VarName1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName1", "VarName2"], "EmptyFieldRule", "auto");

% Import the data
fileExcel1 = readtable("D:\Matlab\fileExcel.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts